### ISSUE TITLE
Demo Segfault

### ISSUE THREAD

**Issue by buddja** [myfreeweb/systemstat#1]
I tried playing around with your library and was surprised to see one of the few segfaults i've seen in rust and running your demo file too. 

```
     Running `target/debug/bin`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr:          Custom(Custom { kind: Other, error: StringError("Not supported") }) }',     ../src/libcore/result.rs:785
stack backtrace:
   1:     0x55a355aeafef - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x55a355aed3eb -     std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x55a355aed06f - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x55a355ae4f3e - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   5:     0x55a355aed631 - std::panicking::begin_panic::he426e15a3766089a
   6:     0x55a355ae58aa - std::panicking::begin_panic_fmt::hdddb415186c241e7
   7:     0x55a355aed5ce - rust_begin_unwind
   8:     0x55a355b22aaf - core::panicking::panic_fmt::hf4e16cb7f0d41a25
   9:     0x55a355ad9f1b - core::result::unwrap_failed::hf40cb93f6f31ec3d
                        at ../src/libcore/macros.rs:29
  10:     0x55a355ad9551 - _<core..result..Result<T, E>>::unwrap::ha10f31560a1ef478
                        at ../src/libcore/result.rs:723
  11:     0x55a355ad81ba - bin::main::h526525808e6ff144
                         at src/main.rs:10
  12:     0x55a355aecca8 - std::panicking::try::call::h852b0d5f2eec25e4
  13:     0x55a355af6cbb - __rust_try
  14:     0x55a355af6c5e - __rust_maybe_catch_panic
  15:     0x55a355aec74e - std::rt::lang_start::hfe4efe1fc39e4a30
  16:     0x55a355ae1cf9 - main
  17:     0x7f9fa817d740 - __libc_start_main
  18:     0x55a355ad7ce8 - _start
  19:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/bin` (exit code: 101)
```

Since I rarely run into segfaults im unsure of how to continue, do you have any ideas as to what could be causeing this?

**Comment by myfreeweb** [comment]
Hi!

Thanks for trying out this library.

That's a panic, not a segfault, and it's a custom error that says "Not 
supported". So, your operating system is not fully supported yet.

I've only implemented full support for FreeBSD and started working on 
Linux support (currently, only memory and load_average are working on 
Linux).

You can always help with implementing the functionality for different 
operating systems ;-)

**Comment by buddja** [comment]
Ok that makes since. Sorry for my ignorance, I've only been working in rust for about 2 months. Also i'd be glad to help (with what little i can) I've been looking for a smaller project to contribute too lately.
